# autostart

# exec-once = $terminal
# exec-once = nm-applet & 
# exec-once = eww daemon
exec-once = waybar
exec-once = dunst
exec-once = swww-daemon
exec-once = hyprctl setcursor "Capitaine Cursors (Gruvbox)" 15
exec-once = xrdb -load /home/daksh/.Xresources
# exec-once = hypridle
exec-once = "/home/daksh/.local/bin/wallpaperchanger" 
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# nvidia electron discord
# exec-once = LIBVA_DRIVER_NAME=i915 vesktop --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy 

# Env/Alias settings
source = ~/.config/hypr/modules/env.conf
# Monitor settings
source = ~/.config/hypr/modules/monitors.conf
# General/Appearance settings
source = ~/.config/hypr/modules/general.conf
# Input/Device settings
source = ~/.config/hypr/modules/input.conf
# Rule settings
source = ~/.config/hypr/modules/rules.conf
# Keybinds settings
source = ~/.config/hypr/modules/binds.conf
