input {
    numlock_by_default = true
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = true
    }
}

gestures {
    workspace_swipe = true
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

