add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

# A minimal left prompt
format = """$all$directory$git_branch${custom.git_status_dirty}$git_status$cmd_duration$status$character"""

# no right prompt
right_format = ""

# Timeout for commands executed by starship (in milliseconds)
command_timeout=2000

[character]
success_symbol = "[❯]()"
error_symbol = "[❯](red)"
vicmd_symbol = "[■]()"
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[nix_shell]
style = 'bold italic dimmed blue'
symbol = '✶'
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[directory]
truncation_length = 1
truncation_symbol = ""
fish_style_pwd_dir_length = 1

# right prompt uses left space padding
[git_branch]
format = '[$branch]($style)'
style = 'bold green'

[git_status]
format = "[($ahead_behind$stashed)]($style) "
style = "cyan"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = "•"
style = "white"
format="[$symbol]($style)"
shell = ["fish", "--no-rcs", "--no-globalrcs"]

[cmd_duration]
format = '[$duration]($style) '

[line_break]
disabled = true

[status]
disabled = false
pipestatus = true
format = '[$symbol$int]($style)'
# symbol = '✘ '
symbol = ''
pipestatus_format = '\[$pipestatus\]($style)'
